import { OrganismPresets } from "@madnesslabs/fireenjin-designer/dist/types/interfaces";

export default {
  default: {
    name: "Default",
    props: {
      apiKey: "AIzaSyAz5C9TRxQ9bUkTwVaD6Yc-Iisw57UslPM",
      markers: [
        {
          payload: {
            job: {
              id: "UXmgvBkzLJQ9eKRR8o7i",
              title: "Test Job",
              status: "respond",
              picture:
                "https://firebasestorage.googleapis.com/v0/b/ftms-ca85b.appspot.com/o/undefined%2F2021-06-24T19%3A37%3A06.309Z.pdf?alt=media&token=4aa1bf9d-b8da-4072-b606-eb01df4d6d76",
              type: "Regular",
              amountBilled: 9.78,
              amountOwed: 9.78,
              cause: null,
              category: null,
              tags: ["imported"],
              address: {
                placeId: "ChIJPfl4qGLQ3ocR9owEFEIQ_os",
                lat: 38.807272,
                lng: -90.7154228,
                full: "353 Westridge Dr, O'Fallon, MO 63366, USA",
                street: "353 Westridge Drive",
                unit: null,
                city: "O'Fallon",
                state: "MO",
                zip: "63366",
                country: "US",
              },
              appointment: null,
              referral: {
                id: "yeyuWV6NBdN7fcE6xqY9GXwRmmi1",
                firstName: "Bobby",
                lastName: "Johnson",
                email: "bobby@madnesslabs.net",
                phone: "3143133351",
              },
              manager: null,
              payables: [],
              createdAt: "2021-04-26T00:50:24.000Z",
            },
          },
          name: "Test Job",
          icon: null,
          position: {
            lat: 38.807272,
            lng: -90.7154228,
          },
        },
        {
          payload: {
            job: {
              id: "DrIo0kPUO1FbntPB5B6H",
              title: "Robert G Johnson Jr",
              status: "respond",
              picture: null,
              type: "Regular",
              amountBilled: 0,
              amountOwed: 0,
              cause: null,
              category: null,
              tags: ["imported"],
              address: {
                placeId: "ChIJgWOehDjb3ocRQpiGyxhcO5o",
                lat: 38.8805932,
                lng: -90.74089610000001,
                full: "1551 Misty River Dr, O'Fallon, MO 63366, USA",
                street: "1551 Misty River Drive",
                unit: null,
                city: "O'Fallon",
                state: "MO",
                zip: "63366",
                country: "US",
              },
              appointment: null,
              referral: {
                id: "yeyuWV6NBdN7fcE6xqY9GXwRmmi1",
                firstName: "Bobby",
                lastName: "Johnson",
                email: "bobby@madnesslabs.net",
                phone: "3143133351",
              },
              manager: null,
              payables: [],
              createdAt: "2021-04-02T16:14:08.000Z",
            },
          },
          name: "Robert G Johnson Jr",
          icon: null,
          position: {
            lat: 38.8805932,
            lng: -90.74089610000001,
          },
        },
        {
          payload: {
            job: {
              id: "XcFgTYNu1nEVG8rIq5yl",
              title: "Lea Teacher",
              status: "review",
              picture: null,
              type: "Regular",
              amountBilled: 13194.25,
              amountOwed: 13194.25,
              cause: null,
              category: 1,
              tags: ["imported"],
              address: {
                placeId: "ChIJpZxzaczX3ocR_XNXEHyjwyM",
                lat: 38.780622,
                lng: -90.6146618,
                full: "13 Julie Ln, St Peters, MO 63376, USA",
                street: "13 Julie Lane",
                unit: null,
                city: "St. Peters",
                state: "MO",
                zip: "63376",
                country: "US",
              },
              appointment: null,
              referral: null,
              manager: {
                id: "HPuxLgahl2XoDaz6S6mP0Yfn1Ip1",
                firstName: "Aaron",
                lastName: "Cutter",
                email: "Aaron@thefloodteam.com",
                phone: "3145469467",
              },
              payables: [],
              createdAt: "2019-07-03T16:32:25.000Z",
            },
          },
          name: "Lea Teacher",
          icon: null,
          position: {
            lat: 38.780622,
            lng: -90.6146618,
          },
        },
      ],
    },
  },
} as OrganismPresets;
